= Spring Boot 样板项目（使用Kotlin与Gradle）

本样板项目基于 https://spring.io/[Spring] 官方的 https://start.spring.io/[Spring Initializr] 生成的 https://spring.io/projects/spring-boot/[Spring Boot] 项目，
并添加一些实用的常见配置，便于在新项目启动时“简单修改POM即可复用”。

同时，本项目也将不断跟进上游最新版本，以便下游项目一站式更新。

目录结构：

----
spring-boot-boilerplate-kotlin
│  .gitattributes
│  .gitignore
│  build.gradle.kts
│  gradlew
│  gradlew.bat
│  LICENSE
│  README.adoc
│  settings.gradle.kts
│  
├─gradle
│  └─wrapper
│          gradle-wrapper.jar
│          gradle-wrapper.properties
│          
└─src
    ├─main
    │  ├─kotlin
    │  │  └─com
    │  │      └─example
    │  │          └─demo
    │  │                  DemoApplication.kt
    │  │                  
    │  └─resources
    │      │  application-dev.yml
    │      │  application-production.yml
    │      │  application-staging.yml
    │      │  application.yml
    │      │  logback-spring.xml
    │      │  logback-spring.xml.aliyun.example
    │      │  logback-spring.xml.file.example
    │      │  logback-spring.xml.jdbc.example
    │      │  
    │      └─static
    │              .gitkeep
    │              
    └─test
        └─kotlin
            └─com
                └─example
                    └─demo
                            DemoApplicationTests.kt
----

== 项目信息

* 构建工具： Gradle （Wrapper 版本： 6.0.1 ）
* Kotlin 版本： 1.3.60

与 https://start.spring.io/[Spring Initializr] 生成的 https://spring.io/projects/spring-boot/[Spring Boot] 项目相比，有如下变动：

* git 行为配置
** 一个通用的 `.gitignore` 文件（规定 git 自动忽略哪些文件）
** 一个通用的 `.gitattributes` 文件（规定 git 对文本格式的处理）
** 为空目录添加 `.gitkeep` 文件（0字节，仅占位，避免空目录被忽略）

* 在 `build.gradle.kts` 中配置了镜像源（阿里云Maven）
** Gradle 的 CDN 在中国大陆已经很快了，因此没有单独配置

* 包含一个基本的 `README.adoc` 自述文件，以便参考 AsciiDoc 语法
** AsciiDoc 兼容 Markdown 语法，可在 `adoc` 中直接写 Markdown

* 配置文件使用YAML （ `application.yml` 取代 `application.properties` ）

* 项目配置集
** 三个 Spring Profile: `dev`, `staging`, `production`
*** 注意：本项目中仅包含 Spring Profile

* Logback 日志配置 `logback-spring.xml`
** 默认根据 Profile 选用控制台输出／文件输出（简单配置）
** 附带样例文件，方便详细配置：
*** `logback-spring.xml.file.example` 文件输出（详细配置）
*** `logback-spring.xml.jdbc.example` 数据库输出（JDBC）
*** `logback-spring.xml.aliyun.example` 阿里云SLS（阿里云日志服务）

== 运行指引

* 如果你使用 IDEA / Spring Tool Suite，直接运行项目即可。

* 如果你不想使用 IDE，可以用命令行的方式运行 Spring Boot 项目，你需要先在本地安装：

** Git
** JDK 1.8 或更高版本

** 执行命令：
[source,sh]
----
git clone https://github.com/yanwenkun/spring-boot-boilerplate-kotlin.git
cd spring-boot-boilerplate-kotlin
./gradlew clean bootRun
----

按 `Ctrl + C` 可终止运行

== 编写中

Gradle 有其灵活的构建方式，不需要对应 Maven Profile 的使用习惯。因此本项目实际只有一套 Spring Profile，勿混淆。

Spring Profile 在 Java/Kotlin 代码中的用法：使用Spring注解： @Profile("staging")
