= Spring Boot 样板项目（使用Kotlin与Gradle）

本样板项目基于 https://spring.io/[Spring] 官方的 https://start.spring.io/[Spring Initializr] 生成的 https://spring.io/projects/spring-boot/[Spring Boot] 项目，
并添加一些实用的常见配置，便于在新项目启动时“简单修改POM即可复用”。

同时，本项目也将不断跟进上游最新版本，以便下游项目一站式更新。

目录结构：

----
spring-boot-boilerplate-kotlin
│  .gitattributes
│  .gitignore
│  build.gradle.kts
│  gradlew
│  gradlew.bat
│  LICENSE
│  README.adoc
│  settings.gradle.kts
│  
├─gradle
│  └─wrapper
│          gradle-wrapper.jar
│          gradle-wrapper.properties
│          
└─src
    ├─main
    │  ├─kotlin
    │  │  └─com
    │  │      └─example
    │  │          └─demo
    │  │                  DemoApplication.kt
    │  │                  
    │  └─resources
    │      │  application-dev.yaml
    │      │  application-production.yaml
    │      │  application-staging.yaml
    │      │  application.yaml
    │      │  logback-spring.xml
    │      │  logback-spring.xml.aliyun.example
    │      │  logback-spring.xml.file.example
    │      │  logback-spring.xml.jdbc.example
    │      │  
    │      └─static
    │              .gitkeep
    │              
    └─test
        └─kotlin
            └─com
                └─example
                    └─demo
                            DemoApplicationTests.kt
----

== 项目信息

* 构建工具： Gradle （Wrapper 版本： 6.0.1 ）
* Kotlin 版本： 1.3.60

与 https://start.spring.io/[Spring Initializr] 生成的 https://spring.io/projects/spring-boot/[Spring Boot] 项目相比，有如下变动：

* git 行为配置
** 一个通用的 `.gitignore` 文件（规定 git 自动忽略哪些文件）
** 一个通用的 `.gitattributes` 文件（规定 git 对文本格式的处理）
** 为空目录添加 `.gitkeep` 文件（0字节，仅占位，避免空目录被忽略）

* Gradle Wrapper 的 CDN 在中国大陆已经很快了，因此没有单独配置
** 为本地 Gradle 全局配置 Maven 镜像源，请参照 <<配置 Maven 镜像源>> 进行配置。

* 包含一个基本的 `README.adoc` 自述文件，以便参考 AsciiDoc 语法
** AsciiDoc 兼容 Markdown 语法，可在 `adoc` 中直接写 Markdown

* 配置文件使用YAML （ `application.yaml` 取代 `application.properties` ）

* 项目配置集
** 三个 Spring Profile: `dev`, `staging`, `production`
*** 注意：本项目中仅包含 Spring Profile

* Logback 日志配置 `logback-spring.xml`
** 默认根据 Profile 选用控制台输出／文件输出（简单配置）
** 附带样例文件，方便详细配置：
*** `logback-spring.xml.file.example` 文件输出（详细配置）
*** `logback-spring.xml.jdbc.example` 数据库输出（JDBC）
*** `logback-spring.xml.aliyun.example` 阿里云SLS（阿里云日志服务）

== 运行指引

* 如果你使用 IDEA / Spring Tool Suite，直接运行项目即可。

* 如果你不想使用 IDE，可以用命令行的方式运行 Spring Boot 项目，你需要先在本地安装：

** Git
** JDK 1.8 或更高版本

** 执行命令：
[source,sh]
----
git clone https://github.com/yanwenkun/spring-boot-boilerplate-kotlin.git
cd spring-boot-boilerplate-kotlin
./gradlew clean bootRun
----

按 `Ctrl + C` 可终止运行

== 修改成你的项目

1. 全局搜索 `DemoApplication` ，并替换为你的程序名称，比如 `SampleApplication` （建议保留 Application 后缀）
2. 全局搜索 `com.example.demo` ，并替换为你的软件包名称，比如 `fun.yanwenkun.sample`
3. 全局搜索 `com.example` ，并替换为你的组织名称，比如 `fun.yanwenkun`
4. 修改 `build.gradle.kts` 中的软件制品信息，并管理你的依赖项
5. 修改代码文件对应的路径、文件名（可通过IDE完成）

== 配置集的使用

Gradle 有其灵活的构建方式，不需要对应 Maven Profile 的使用习惯。因此本项目实际只有一套 Spring Profile，勿混淆。

=== Profile 用法

* Spring Profile 在 Java/Kotlin 代码中的用法：
** 使用Spring注解： `@Profile("staging")`

=== 指定配置集

注意：同一时间只能有一个 Spring Profile 激活

* 方法1：运行时指定参数
[source,sh]
----
java -jar demo.jar --spring.profiles.active=dev
----

* 方法2：修改 `application.yaml` 中的 `spring:profiles:active` 属性

* 方法3：使用环境变量，使 Spring Boot 程序运行时直接调用不同配置集：
[source,sh]
----
export SPRING_PROFILES_ACTIVE=production
----

== 配置集的理解

* Profile 直译即“档案”，此处理解为配置、配置集

* 本项目中的3个 Profile 是有意选择的单词，长度递增：
** 开发阶段： `dev`
** 验证阶段： `staging`
** 生产阶段： `production`

=== Staging

* staging 翻译成“验证阶段”
** 如果翻译成“测试阶段”，流程上太靠前
** 如果翻译成“预发布阶段”，流程上太靠后
** “验证”更为概括而居中。本项目中仅包含这一中间阶段，如有需要可以再添加细分
** 理解 Staging 阶段在敏捷开发中的意义： http://www.shuker.top/technology/devops/deployments-best-practices/

=== 概念上的简化

* 开发、验证、生产：
 1. 既是软件生命周期中的“阶段”
 2. 也是运维与服务治理中的“环境”
* 这是一个“偷懒”的做法，将阶段和环境合为一谈，主要目的在于减少心智负担
** 但扩大开发规模的时候，还是要注意概念上的区分

== 日志的配置

=== 配置 `application-{$profile}.yaml`

* 本项目中的各 Spring 配置文件已包含少量日志配置供参考
* 比如最常用的 `logging:level:something: DEBUG`
* 可借助 IDE 翻阅 logging 下的可配置项
* 完整配置项可参考： https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html[Common Application properties]

=== 配置 `logback-spring.xml`

* 如果一些参数没有被 Spring 属性化，需要单独配置 `logback-spring.xml`
* 进一步的配置请参考 `src/main/resources` 下的 `.example` 文件
* 如果感到困惑，请先参考 `logback-spring.xml.file.example`
* 控制台输出的配置较为简单，因此没有单独列出

=== 一些原则

* 原则上，尽量多配置于 `application-{$profile}.yaml` 中，少配置于 `logback-spring.xml` 中，便于管理，也减少文件长度
* 编写代码时不要用 System.out.println() ，而是使用 Slf4j 分等级记录日志
** 可用等级（从低到高）： `TRACE` `DEBUG` `INFO` `WARN` `ERROR`
* 生产环境建议关闭控制台输出


= 项目之外

== JDK 的选择

=== Oracle JDK 的收费背景

* 在以往几乎完全免费的 https://www.oracle.com/technetwork/java/javase/downloads/index.html[Oracle JDK]，从2019年开始，只对开发、个人使用免费，用于生产环境需要付费。
* 而 https://jdk.java.net/[Oracle OpenJDK] 只更新最新GA大版本，每当新的大版本GA，老版本即停止更新。
** Oracle 这么做是为了鼓励开发者跟进新版本，同时也扩大老版本的维护收费。
** 但是企业开发，“追新”是为了保持先进、与主流同步，“追最新”则容易踩坑、增加成本。所谓“领先一步是先驱，领先两步是先烈” :)

=== 使用其它提供方的 OpenJDK

考虑以下几点：

* 有健壮支持
* 完全免费
* 开源

推荐如下：

* https://adoptopenjdk.net/[AdoptOpenJDK]
** 来自 Java 社区重要成员支持的 OpenJDK
** 目前涵盖 `8` ~ `13` 所有大版本
** 除了 JDK 之外，每个版本还提供 JRE
** 除了 `HotSpot` JVM 之外，还提供 `OpenJ9` JVM （来自 IBM 开源的 JVM，为云环境、容器化优化，内存占用小）
** OpenJ9 可选择 Large Heap 预配置版本（堆内存 > 57 GiB），该配置以更大内存占用为代价，提高吞吐与响应，大幅减少 GC 时的暂停时间

* https://www.aliyun.com/product/dragonwell[Alibaba Dragonwell]
** 阿里巴巴开源的 OpenJDK
** 目前版本只有 `8`，即将发布 `11`
** 目前只支持 `Linux x86-64`

* https://aws.amazon.com/corretto[Amazon Corretto]
** 亚马逊开源的 OpenJDK
** 为 `8` 和 `11` 提供长期支持

如果你感到选择困难，请使用 https://adoptopenjdk.net/?variant=openjdk11&jvmVariant=hotspot[AdoptOpenJDK11+HotSpot] 。

== 配置 Maven 镜像源

在中国大陆访问 Maven 官方源一般会很慢，建议使用镜像源。

* 不推荐直接在 `build.gradle.kts` 中配置仓库来源
** 如果是开源项目，会影响身处国外的开发者
** 不利于 CI 的管理

如何为本地 Gradle 全局配置 Maven 镜像源：

将 link:docs/gradle/mirrors.init.gradle.kts[mirrors.init.gradle.kts] 复制到【 用户主目录/.gradle/init.d/ 】下。
或执行命令：

[source,sh]
----
mkdir ~/.gradle/init.d/
cp docs/gradle/mirrors.init.gradle.kts ~/.gradle/init.d/
----

该配置对运行在本地的 Gradle、Gradle Wrapper 均有效。

== 许可

使用与 https://github.com/spring-projects/spring-boot[Spring Boot] 一致的 Apache License 2.0 许可。
