# 验证阶段 Profile 配置
# 继承 application.yml 中的配置，并覆盖

logging:
  file:
    name: ./log/${spring.application.name}.${spring.profiles.active}.log # 可在文件名前直接带上子目录
#    path: ${LOG_FILE:-${LOG_PATH:-${LOG_TEMP:-${java.io.tmpdir:-/tmp}}}} # 指向OS临时目录
